name: Check flake
on:
  push:
    path:
      - ./**.nix
      - ./flake.lock
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run `nix flake check`
        run: nix flake check --keep-going --verbose
  buildAndPush:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build image
        run: |
          nix build --print-build-logs '.#lix-gha-image'
          docker load <"$(realpath result)" 
          docker image list
      - name: Push docker image
        run: |
          docker image tag "lix-gha-image:latest" "ghcr.io/jalil-salame/lix-gha-image:latest"
          docker push "ghcr.io/jalil-salame/lix-gha-image:latest"
