name: Check flake
on:
  push:
    path:
      - ./**.nix
      - ./flake.lock
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run `nix flake check`
        run: nix flake check --keep-going-verbose
  buildAndPush:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 'jalil-salame/lix-gha:latest'
